# -*- coding: utf-8 -*-
"""Figure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U_eS1ch-fDyxAIsCZvOoMm4jioLrxFn
"""

class Figure(ABC):
    def __init__(self, points: tuple[tuple, ...]):
        self.points = points
        self.square = self.calculateSquare()
        self.perimeter = self.calculatePerimeter()

    @abstractmethod
    def calculatePerimeter(self) -> float:
        pass

    @abstractmethod
    def calculateSquare(self) -> float:
        pass

    @abstractmethod
    def __str__(self) -> str:
        pass

    @classmethod
    @abstractmethod
    def constructFromSeries(cls,series: pd.Series) -> object:
        """construct instance from pandas.Series"""

    @abstractmethod
    def graphFigure(self):
        """Draw figure via matplotlib.pyplot"""
        pass