# -*- coding: utf-8 -*-
"""Rectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U_eS1ch-fDyxAIsCZvOoMm4jioLrxFn
"""

class Rectangle(Figure):
    def __init__(self, points):
        self.points = points
        self.square = self.calculateSquare()
        self.perimeter = self.calculatePerimeter()

    def calculatePerimeter(self):
        return 2 * (self.points[1][0] - self.points[0][0]) + 2 * (self.points[1][1] - self.points[0][1])

    def calculateSquare(self):
        return (self.points[1][0] - self.points[0][0]) * (self.points[1][1] - self.points[0][1])

    def __str__(self):
        s=''
        s+='"rectangle"'
        s+= ';'
        s+=str(self.calculateSquare())
        s+= ';'
        s+=str(self.calculatePerimeter())
        s+=';('
        s+=str(self.points[0][0])
        s+=':'
        s+=str(self.points[0][1])
        s+=');('
        s+=str(self.points[1][0])
        s+=':'
        s+=str(self.points[1][1])
        s+=')'
        return s

    def constructFromSeries(cls,series: pd.Series):
        points = tuple((tuple(series.iloc[1:3])[0].split(':'), series.iloc[2]))
        return cls(points)

    def graphFigure(self):
        fig, ax = plt.subplots()
        ax.set_xlim(- self.points[0][0] - (self.points[1][0] - self.points[0][0]), self.points[1][0] + (self.points[1][0] - self.points[0][0]))
        ax.set_ylim(- self.points[0][1] - (self.points[1][1] - self.points[0][1]), self.points[1][1] + (self.points[1][1] - self.points[0][1]))
        ax.add_patch(plt.Rectangle(self.points[0], (self.points[1][0] - self.points[0][0]), (self.points[1][1] - self.points[0][1])))
        ax.set_aspect(1)
        plt.show()